### ISSUE TITLE
redefinition of 'bool wifiok'

### ISSUE THREAD

**Issue by andrewbpowers** [alanesq/BasicWebserver#2]
Redefinition of 'bool wifiok' in wifi.h (line 45):
`bool wifiok = 0;                // flag if wifi connection is ok`

First definition in BasicWebServer.ino (line 98):
`bool wifiok = 0;                        // flag if wifi connection is ok`

**Comment by alanesq** [comment]
Thanks

I have corrected these
Odd thing is, I am sure I already fixed these a few weeks back but it seems to have reverted back?

**Comment by andrewbpowers** [comment]
It can happen. :-) I thought maybe it is a little help if I hint at it.

Best regards stay healthy!

**Comment by alanesq** [comment]
fixed
